### ISSUE TITLE
Issue with login form

### ISSUE THREAD

**Issue by danielkellyio** [yevgeller/vueschool-forum#1]
Hey Eugene, 
I'm going to move the convo here just for the sake of not crowding the comments in the video.
Checkout [this video](https://drive.google.com/file/d/1T6haxBZbH-sVHYXkgr2i62BTIkRICLjs/view?usp=sharing) and let me know if you still need anything further after trying the suggestions. 

Thanks!

**Comment by yevgeller** [comment]
Daniel,

Thanks for the video! 

Sorry, I should have been more specific. The SignIn page captures credentials just fine, and I'm seeing the same behavior as you do. However, when "signInWithEmailAndPassword" in auth.js is dispatched to be called, both email and password are undefined:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/2040334/152469508-08685437-be06-483c-9727-9cd8b706bf5f.png">

Hence firestore's complain and the error message. So somehow passing arguments to vuex wipes them out.

I have tried your suggestions: 
- deleted node_modules and ran npm_install
- Updated node.js (I was running 14, apparently doing "npm install node" is a bad idea, spent an hour trying to figure out some weird error and why I have node 17 if I'm installing 16. Now I'm running node 16.
- Rebooted (many times while installing/uninstalling node)

and I still see the same behavior.

Thanks again!!

**Comment by danielkellyio** [comment]
Looking more into this now but just a quick tip on managing node versions. NVM is super helpful with this. It lets you download and use different node versions at will.

https://github.com/nvm-sh/nvm

**Comment by danielkellyio** [comment]
Ah, I see the issue. On the action definition itself you're missing the context as the first arg. The payload is always the second argument like so:

```signInWithEmailAndPassword(context, { email, password }) {```

Changing it worked for me. Does that get it working for you?

**Comment by yevgeller** [comment]
Yes, that fixed it, thank you so much!!

I have the eslint rule for no-unused-variables set and it cleared out that context variable since context wasn't used. 

Thanks again!!
